language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra

    # Additional components
    #- extra-google-google_play_services
    #- addon-google_apis-google-19

    # Specify at least one system image, if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

  licenses:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - gradle wrapper --gradle-version 4.1
  - chmod a+x gradlew

script:
 - ./gradlew :app:assembleRlsRelease